version: "3"
services:
  server:
    image: clickhouse/clickhouse-server:head-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client
    command: [ '--host', 'server' ]
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker-support/mysql-init-files/:/docker-entrypoint-initdb.d/
    restart: always
    container_name: mmc
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - '3306:3306'

   